fix: use correct season for anime
manami-project/modb-kitsu pull request #2
Opened 2020-09-12 22:16 UTC by wopian

The season matching is 1 month ahead, leaving the earliest anime (usually a week or two) of each season in the previous season.

For consumers, the current behaviour would appear correct as the "Winter" season is media that airs between January and March, but that does not account for the edge cases like this.

`Youkai Watch Jam: Youkai Gakuen Y - N to no Souguu` started on December 27th 2019:

- `modb-kitsu` treats it as Fall 2019
- [`anilist`](https://anilist.co/anime/113472/Youkai-Watch-Jam-Youkai-Gakuen-Y--N-to-no-Souguu) treats it as Winter 2020
- [`kitsu`](https://kitsu.io/anime/youkai-watch-jam-youkai-gakuen-y-n-to-no-souguu) treats it as Winter 2020
- [`myanimelist`](https://myanimelist.net/anime/40714/Youkai_Watch_Jam__Youkai_Gakuen_Y_-_N_to_no_Souguu) treats it as Winter 2020

2020-09-13 16:01 UTC, manami-project commented
Hi @wopian,
thank you very much for your pull request. I'll have a look at it. First thing I noticed is the change for github actions. Do you mind creating a separate PR for this?

2020-09-13 18:40 UTC, manami-project commented
For the default case the current code seems correct to me. Various sources list it the same as the current code:
See [this blog post](https://manga.tokyo/columns/what-is-a-cour-and-a-season-in-anime/), the [wikipedia list](https://en.wikipedia.org/wiki/2019_in_anime) or [this reddit post](https://www.reddit.com/r/anime/comments/30shaz/how_do_anime_seasons_work/cpve53j/?utm_source=reddit&utm_medium=web2x&context=3)
Interesting is that tv drama seem to have the same season. [source](https://en.wikipedia.org/wiki/Japanese_television_drama)

Yes, there might be some edge cases. One example that comes to my mind are series whose first episode premiered weeks before the regular scheduled start. However since this is a very generic solution based on air dates, I wouldn't change the logic which is correct for most cases, in order to match some edge cases which then could create false results for quite a few others.

2020-09-15 10:04 UTC, manami-project requested changes
So from my perspective the identification of the season is fine as it is (winter = 1,2,3 and so on). I don't see any possibility to track edge cases. The change for github actions is fine, but I'd love to see it in a separaete PR.

2020-09-16 16:15 UTC, wopian commented
> For the default case the current code seems correct to me. Various sources list it the same as the current code:
> See [this blog post](https://manga.tokyo/columns/what-is-a-cour-and-a-season-in-anime/)

The blog post talks about anime that air during the seasons (January to March etc). Youkai Watch Jam aired through those seasons with 4 days in _Autumn 2019_, even the Japanese [Anikore.jp](https://www.anikore.jp/anime/12656/) site lists it as Winter 2020 (`放送時期：2020年冬アニメ`)

>the [wikipedia list](https://en.wikipedia.org/wiki/2019_in_anime)

The Wikipedia page lists anime by airdate from 1st January to 31 December. It doesn't consider seasons.

> or [this reddit post](https://www.reddit.com/r/anime/comments/30shaz/how_do_anime_seasons_work/cpve53j/?utm_source=reddit&utm_medium=web2x&context=3)

The reddit post says "approximately three month[s]"

> Interesting is that tv drama seem to have the same season. [source](https://en.wikipedia.org/wiki/Japanese_television_drama)

Japan's television scheduling uses 4 3-month cours (1-4, January-October and Winter-Autumn are interchangeable). The Japanese Television Drama wiki states "Some series may start in another month though it may still be counted as a series of a specific season"

---

Films do not release in cours and are not associated with any specific season - almost all\* trackers omit the season altogether for non-TV media.

<sub>\* I believe Kitsu is the only one that calculates a season for films.</sub>

2020-09-16 19:59 UTC, manami-project commented
>Some series may start in another month though it may still be counted as a series of a specific season
That is probably the main problem if the season is assumed by its starting month and not set directly as a value. At least in case this applies to anime as well.

>The Wikipedia page lists anime by airdate from 1st January to 31 December. It doesn't consider seasons.
I was referring to the list of television series having the same months as the current mapping as start dates. Based on this, I concluded the boundaries of the seasons.

I've been mainly working with MAL so far. They list an extra field "premiered" which probably has been set manually (just an assumption). All other anime on their site not listing this field are still part of a season (including movies). This season affiliation might be done automatically as well. They also seem to use the same months for their mapping:

[Mini Yuri on MAL = Summer](https://myanimelist.net/anime/40369/Mini_Yuri)
[Mini Yuri on Kitsu = Fall](https://kitsu.io/anime/mini-yuri)

[Hoozuki no Reitetsu 2nd Season OVA on MAL = Summer](https://myanimelist.net/anime/39538/Hoozuki_no_Reitetsu_2nd_Season_OVA)
[Hoozuki no Reitetsu 2nd Season OVA on Kitsu = Fall](https://kitsu.io/anime/Hoozuki-no-Reitetsu-Second-Season-OVA)

>I believe Kitsu is the only one that displays a season for films.
MAL actually affiliates movies with a season (check "seasonal anime" page) and also displays it (at least on their mobile site).
Notify.moe also displays the season for movies. [Example](https://notify.moe/anime/Zw_PpFimg)

Just working by single examples probably doesn't get us far. Because here is a counterexample. A september release listed as summer season on mal/notify and fall on kitsu.

[Beatless Final Stage (MAL, premiered is actually set, SUMMER)](https://myanimelist.net/anime/38020/Beatless_Final_Stage)
[Beatless Final Stage (notify, SUMMER)](https://notify.moe/anime/ohp6X3vmg)
[Beatless Final Stage (kitsu, Fall)](https://kitsu.io/anime/beatless-final-stage)

So notify uses the current mapping as well. [Utils.go](https://github.com/animenotifier/notify.moe/blob/go/arn/Utils.go)

Is there maybe a source that determines which mapping is more accurate or if there is actually a correct mapping?
I can't really say that the change in the PR is better in general. If this is the mapping that kitsu.io uses to show the season string, then I would consider merging your PR for modb-kitsu to be in sync with the kitsu data. However I would keep the current mapping for the other repositories, so that they are in sync with their respective source data.

2020-09-17 00:35 UTC, wopian commented
> I've been mainly working with MAL so far. They list an extra field "premiered" which probably has been set manually (just an assumption). All other anime on their site not listing this field are still part of a season (including movies). This season affiliation might be done automatically as well. They also seem to use the same months for their mapping:

I would have changed the implementation to check its the last week of the season (to catch those airing slightly before the 1st). However, it's most likely not worth the extra complexity for a small increase in accuracy and because of the trackers having their own different edge cases on handling edge case anime. 

> Just working by single examples probably doesn't get us far. Because here is a counterexample. A september release listed as summer season on mal/notify and fall on kitsu.

Like here for the Beatless Final, MAL (manual?) and Notify (automatic) are correct as it all aired back-to-back over a few days in the last week of the last season (it started and ended in September), while Kitsu (automatic) doesn't check the end date (like the others, but offsets to catch those starting a few days early) and presumes it would have aired through the next season (à la Youkai Watch Jam), which it didn't.

If the season calculation went 1 week into the previous month and checked the end date was not before the season "start" (i.e starts on 24th Dec and finishes on 29th Dec, before 1st Jan) then I'd say it'd be mostly edge case free (or less than current) and the most accurate in putting media into the correct season. A few shows would be out of sync with different trackers and falls into the issue of the added complexity not being worth the effort or reward mentioned at the beginning.

> If this is the mapping that kitsu.io uses to show the season string, then I would consider merging your PR for modb-kitsu to be in sync with the kitsu data

This is the mapping that Kitsu uses on the [backend](https://github.com/hummingbird-me/kitsu-server/blob/dc0cc0b5d3981cc2682d5e626d26976bd65549cd/app/models/anime.rb#L91-L98) and [frontend](https://github.com/hummingbird-me/kitsu-web/blob/c0a609bb95529fb5d6676630875e6acec61dd74c/app/components/media/media-information.js#L29-L43).

> However I would keep the current mapping for the other repositories, so that they are in sync with their respective source data.

This is the best option for now and to keep data in-sync with the respective trackers.

2020-09-17 06:24 UTC, manami-project requested changes
Would be great if you could create a separate PR for the CI.

2020-09-17 06:24 UTC, manami-project commented on .github/workflows/build.yml
> +  pull_request:
I think that in this case it should be enough to just [extend the trigger](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#example-using-a-list-of-events) on line 3. This way you can omit the duplicated definition.

```
on: [push, pull_request]
```

2020-09-17 12:30 UTC, wopian commented on .github/workflows/build.yml
> +  pull_request:
You cannot extend the `on` configuration with that syntax. 

> If you need to specify activity types or configuration for an event, you must configure each event separately. You must append a colon (:) to all events, including events without configuration.

2020-09-17 15:41 UTC, merged

2020-09-17 15:41 UTC, manami-project commented
Thank you for your contribution.